version: '3'

services:
  pytest-host:
    container_name: pytest-host
    build: .
    depends_on:
     - selenium-hub
     - selenium-chrome
    entrypoint: [
        "./wait-for-it.sh", "-t", "15", "selenium-chrome:5555", "--", "pytest",
        "--remote", "--rmt-host=selenium-hub"
    ]
    volumes:
      - ./remote_reports/:/selenium_tests/reports/
      - ./remote_reports/:/selenium_tests/screenshots/
    networks:
      selenium_net: {}

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
    networks:
      selenium_net: {}

  selenium-chrome:
    container_name: selenium-chrome
    image: selenium/node-chrome:3.141.59-vanadium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      selenium_net: {}

networks:
  selenium_net:
    driver: bridge